### ISSUE TITLE
Run describe block isolated

### ISSUE THREAD

**Issue by mscoobby** [ericelliott/riteway#133]
Hello, I was wondering is there a way to isolate the describe block from each other or clean after?
My case is that first I test a `register()` function that attaches an object to the `global` variable and then I have `instance ()` function that is trying to access that object. The goal is to test the two functions separately so that `instance()` should not see the object before `registe()` is called.
Is there are way to achieve this with RITEway?

**Comment by ericelliott** [comment]
First, you should very rarely need to manipulate global variables. Ask yourself carefully if you really need to do that. Usually, the answer is no. Once in a million times, maybe the answer is yes. Assuming the answer is yes:

If `instance()` really is dependent on the global variable set by `register()` those functions are tightly coupled and can't be unit tested independently. You will need to create a single describe block that intentionally *does not* isolate `instance()` from `register()` in order to properly test `instance()`.

In your `instance()` test, step one will be to call `register()` to set the global variable. Then test `instance()`.

That said, assuming that nothing else uses the global from `register()` you need to `delete global.whatever` at the end of your `instance()` and `global()` tests, so that they do not interfere with other tests which depend on that global setting.

Closing because none of this is particular to RITEway. The answer would be the same for any testing framework.
